let stockProductos = [
    {id: 1, nombre: "Fuente Corsair VS500 500 W 80 Plus White", tipo: "placa", cantidad: 1, precio: 6700, talle: "L", img: './img/fuente.jpeg'},
    {id: 2, nombre: "Placa De Video LHR GeForce RTX 3060 12Gb Asus Rog Strix Gaming Oc", tipo: "buzo", cantidad: 1, precio: 200000, talle: "L", img: './img/placa-video.jpeg'},
    {id: 3, nombre: "Memoria Ram DDR4 - 8Gb 2666 Mhz Beast Kingston Fury Rgb", tipo: "buzo", cantidad: 1, precio: 6500, talle: "M", img: './img/memoria-ram.jpeg'},
    {id: 4, nombre: "Monitor Led 24 Samsung Full Hd 75Hz IPS T350FHL", tipo: "buzo", cantidad: 1, precio: 30000, talle: "M", img: './img/Monitor.jpeg'},
    {id: 5, nombre: "Teclado Galax Stealth 03 Mecanico Azul", tipo: "buzo", cantidad: 1, precio: 7000, talle: "S", img: './img/TecladosYMouses/1.jpeg'},
    {id: 6, nombre: "Placa De Video GeForce GTX 1660Ti 6Gb Gainward Pegasus", tipo: "buzo", cantidad: 1, precio: 150000, talle: "S", img: './img/PlacasDeVideo/3.jpeg'},
    {id: 7, nombre: "Gabinete Mid Tower Gamemax H601 BR Negro y Rojo", tipo: "remera", cantidad: 1,  precio: 5500, talle: "L", img: './img/Gabinetes/4.jpeg'},
    {id: 8, nombre: "Auricular Gamer Logitech G435 Azul", tipo: "remera", cantidad: 1,  precio: 12400, talle: "L", img: './img/AuricularesYMicrofonos/12.jpeg'},
    {id: 9, nombre: "Motherboard AM4 - Asus Prime A320M-K", tipo: "remera", cantidad: 1,  precio: 7100, talle: "M", img: './img/Motherboards/mothernueva.jpeg'},
    {id: 10, nombre: "Memoria Ram DDR4 - 32Gb 2x16 3600 Mhz Kingston Fury Renegade Rgb", tipo: "remera", cantidad: 1,  precio: 34000, talle: "M", img: './img/MemoriasRam/14.jpeg'},
    {id: 11, nombre: "Cámara Web Logitech C930E 1080P", tipo: "remera", cantidad: 1, precio: 11000, talle: "S", img: './img/CamarasWeb/7.jpeg'},
    {id: 12, nombre: "Auricular Gamer Astro A20 Inalámbrico", tipo: "remera", cantidad: 1,  precio: 13400, talle: "S", img: './img/AuricularesYMicrofonos/9.jpeg'},
    {id: 13, nombre: "Fuente Gigabyte 1000W 80 Plus Gold", tipo: "camisa", cantidad: 1,  precio: 900, talle: "L", img: './img/FuentesDePoder/12.jpeg'},
    {id: 14, nombre: "Motherboard 1200 11°Gen - Gigabyte GA-Z590 AORUS PRO AX", tipo: "camisa", cantidad: 1,  precio: 61400, talle: "S", img: './img/Motherboards/placa-madre-gamer-wifi-rgb_40209_1.jpeg'},
    {id: 15, nombre: "Monitor Gamer 27 LG Full Hd 240Hz 27 GP750-B", tipo: "camisa", cantidad: 1,  precio: 95000, talle: "L", img: './img/Monitores/16.jpeg'},
    {id: 16, nombre: "Procesador Intel Core i5 12600K 4.9 Ghz Alder Lake 1700 Sin Cooler", tipo: "camisa", cantidad: 1,  precio: 51600, talle: "S", img: './img/Procesadores/11.jpeg'},
    {id: 17, nombre: "Micrófono Blue Snowball Ice Usb Black", tipo: "camisa", cantidad: 1,  precio: 7500, talle: "S", img: './img/AuricularesYMicrofonos/23.jpeg'},
    {id: 18, nombre: "Mouse Gamer Corsair Harpoon Rgb Inalámbrico", tipo: "camisa", cantidad: 1,  precio: 8700, talle: "M", img: './img/TecladosYMouses/22.jpeg'},
    {id: 19, nombre: "Motherboard AM4 - Asrock A320M-HDV", tipo: "pantalon", cantidad: 1,  precio: 9600, talle: "L", img: './img/Motherboards/motherboard-asrock-am4_41249_1.jpeg'},
    {id: 20, nombre: "Gabinete Mid Tower Cooler Master Masterbox MB511 ARGB", tipo: "pantalon", cantidad: 1,  precio: 12300, talle: "L", img: './img/Gabinetes/18.jpeg'},
    {id: 21, nombre: "Fuente Aerocool Cylon 500W Rgb 80 Plus Bronze", tipo: "pantalon", cantidad: 1,  precio: 7300, talle: "M", img: './img/FuentesDePoder/13.jpeg'},
    {id: 22, nombre: "Micrófono Elgato Wave 3", tipo: "pantalon", cantidad: 1,  precio: 31600, talle: "M", img: './img/AuricularesYMicrofonos/24.jpeg'},
    {id: 23, nombre: "Auricular Gamer Astro A50 Ps4 y Pc + Base Inalámbrico", tipo: "pantalon", cantidad: 1, precio: 35700, talle: "S", img: './img/AuricularesYMicrofonos/19.jpeg'},
    {id: 24, nombre: "Memoria Ram SODIMM DDR4 - 16Gb 2666 Mhz Kingston", tipo: "pantalon", cantidad: 1,  precio: 12000, talle: "S", img: './img/MemoriasRam/18.jpeg'},
]